backend:
  name: github
  repo: Deividsenbcn/jaleareal
  branch: main
  base_url: https://sveltia-cms-auth.multipreulaplana.workers.dev

media_folder: "assets/img"
public_folder: "/assets/img"

locale: "es"

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción SEO", name: "description", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - label: "Categoría"
        name: "categories"
        widget: "select"
        options:
          - { label: "Jalea Real", value: "jalea-real" }
          - { label: "Propóleo", value: "propoleo" }
          - { label: "Miel", value: "miel" }
          - { label: "Recetas", value: "recetas" }
          - { label: "Estudios", value: "estudios" }
          - { label: "Cera de Abeja", value: "cera-de-abeja" }
          - { label: "Polen", value: "polen" }
      - { label: "Imagen destacada", name: "thumbnail", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
